title: Ibrahim Shuaib — SEO Content Engine OS™
description: >-
  AI systems and SEO strategies for solo founders
  who want organic traffic without agencies.
author: Ibrahim Shuaib
email: ibrahimshuaib@gmail.com
url: "https://blog.ibrahimshuaib.com"
baseurl: ""

theme: minima
minima:
  skin: dark
  logo: /assets/images/logo.svg
  date_format: "%B %-d, %Y"
  social_links:
    - { platform: linkedin,
        user_url: "https://www.linkedin.com/in/ibrahim-shuaib-2453252aa/" }
    - { platform: twitter,
        user_url: "https://www.x.com/IbrahimSEOOS"  }

show_excerpts: true
excerpt_separator: "<!--more-->"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Ibrahim Shuaib"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
